---
author: "Fernando Alvarado"
output: html_document
---


```{r setup, include=FALSE}
#Empezamos limpiando nuestro ambiente
rm(list = ls(all.names = TRUE))


# Configuración global de los bloques de código (chunk's)
knitr::opts_chunk$set(
	echo = FALSE,
	fig.align = "center",
	fig.dim = c(5.0, 4.0),
	fig.pos = "H",
#Agregamos configuraciones para evitar mensajes de advertencias y de errores en el archivo
	message = FALSE,
	warning = FALSE,
	error = F
)

#Librerias necesarias
library(tidyverse)
library(ggplot2)
library(factoextra)
library(dplyr)
library(esquisse)
library(scatterplot3d)


```


# Analisis de las posiciones de la Liga Premier de Inglaterra de la temporada 2019-2020

```{r}
#Cargamos los datos
setwd("C:/Users/ferna/Documents/Estadistica_Aplicada/Analisis_Multivariado/Tarea_3/Eje_6/Data")
#Leyendo un txt
datos <- read.csv("EPL_19_20.txt", header = TRUE, stringsAsFactors = FALSE)

#datos <- read.table("EPL_19_20.txt", header = TRUE)

```


```{r}
head(datos)
```


Nuestros datos contiene la tabla de posiciones de la Liga Premier de Inglaterra de la temporada 2019-2020. contando con los siguientes campos 
 **Team**, **W** *(wins)*, **D** *(draws)* ,**L** *(losses)* , **GF** *(goals for)* , **GA** *(goals against)* , **GD** *(goal difference)*


```{r PCA}
#Realizamos un analisis de componentes principales

#Limpieza d elos datos, para que todos nuestros datos sean numericos 
datos_numericos <- datos[,-1] #Quirando la primera columna de los nombres de los equipos
rownames(datos_numericos) <- datos$Team  #Paea seguir conservando los nombres de los equipos en nuestro DF


pca <- prcomp(datos_numericos, scale. = TRUE)

summary(pca)






```

```{r}
#Grafica del Bracito 
fviz_eig(pca, addlabels = TRUE, ylim = c(0, 100))
```


```{r}
print(pca$rotation)
```
GD  y D   
```{r}
fviz_pca_var(pca, col.var = "contrib", gradient.cols = c("white", "blue", "red"))

```




```{r}
#Grafica 
fviz_pca_biplot(pca, repel = TRUE, col.var = "steelblue", col.ind = "gray30")
```


```{r}


data_reg <- datos %>% dplyr::select(Team,W, GD, D)

data_reg
```


```{r}
#esquisser(data_reg)

```


```{r}
ggplot(data_reg) +
  aes(x = W, y = GD, colour = Team, size = D) +
  geom_point() +
  scale_color_hue(direction = 1) +
  theme_minimal()

```










```{r}
# Instalar si no lo tienes

# Librería


# Graficar
scatterplot3d(x = datos$GD,
              y = datos$D,
              z = datos$W,
              type = "p",    # puntos
              highlight.3d = TRUE,
              angle = 55,
              pch = 16,
              main = "W en función de GD y D")

# Ajustar modelo
modelo <- lm(W ~ GD + D, data = datos)

# Añadir plano de regresión
scatterplot3d(datos$GD, datos$D, datos$W,
              pch = 16,
              angle = 55,
              main = "Plano de regresión")

# Plano de regresión
s3d <- scatterplot3d(datos$GD, datos$D, datos$W, type="p")
s3d$plane3d(modelo)

```






















































































